import type { ApiClient as AutoGeneratedClient } from './gen/client'
import type { ClientDefinition } from './types'

export type CallAction<_C extends ClientDefinition> = AutoGeneratedClient['callAction']

export type CreateConversation<_C extends ClientDefinition> = AutoGeneratedClient['createConversation']
export type ListConversations<_C extends ClientDefinition> = AutoGeneratedClient['listConversations']
export type GetOrCreateConversation<_C extends ClientDefinition> = AutoGeneratedClient['getOrCreateConversation']
export type UpdateConversation<_C extends ClientDefinition> = AutoGeneratedClient['updateConversation']

export type CreateEvent<_C extends ClientDefinition> = AutoGeneratedClient['createEvent']
export type ListEvents<_C extends ClientDefinition> = AutoGeneratedClient['listEvents']

export type CreateMessage<_C extends ClientDefinition> = AutoGeneratedClient['createMessage']
export type GetOrCreateMessage<_C extends ClientDefinition> = AutoGeneratedClient['getOrCreateMessage']
export type UpdateMessage<_C extends ClientDefinition> = AutoGeneratedClient['updateMessage']
export type ListMessages<_C extends ClientDefinition> = AutoGeneratedClient['listMessages']

export type CreateUser<_C extends ClientDefinition> = AutoGeneratedClient['createUser']
export type ListUsers<_C extends ClientDefinition> = AutoGeneratedClient['listUsers']
export type GetOrCreateUser<_C extends ClientDefinition> = AutoGeneratedClient['getOrCreateUser']
export type UpdateUser<_C extends ClientDefinition> = AutoGeneratedClient['updateUser']

export type GetState<_C extends ClientDefinition> = AutoGeneratedClient['getState']
export type SetState<_C extends ClientDefinition> = AutoGeneratedClient['setState']
export type PatchState<_C extends ClientDefinition> = AutoGeneratedClient['patchState']

// not typeable
export type GetConversation<_C extends ClientDefinition> = AutoGeneratedClient['getConversation']
export type DeleteConversation<_C extends ClientDefinition> = AutoGeneratedClient['deleteConversation']

export type GetEvent<_C extends ClientDefinition> = AutoGeneratedClient['getEvent']

export type GetMessage<_C extends ClientDefinition> = AutoGeneratedClient['getMessage']
export type DeleteMessage<_C extends ClientDefinition> = AutoGeneratedClient['deleteMessage']

export type GetUser<_C extends ClientDefinition> = AutoGeneratedClient['getUser']
export type DeleteUser<_C extends ClientDefinition> = AutoGeneratedClient['deleteUser']

// administation routes
export type ConfigureIntegration<_C extends ClientDefinition> = AutoGeneratedClient['configureIntegration']
export type ListPublicIntegrations<_C extends ClientDefinition> = AutoGeneratedClient['listPublicIntegrations']
export type GetPublicIntegrationById<_C extends ClientDefinition> = AutoGeneratedClient['getPublicIntegrationById']
export type GetPublicIntegration<_C extends ClientDefinition> = AutoGeneratedClient['getPublicIntegration']
export type CreateBot<_C extends ClientDefinition> = AutoGeneratedClient['createBot']
export type UpdateBot<_C extends ClientDefinition> = AutoGeneratedClient['updateBot']
export type TransferBot<_C extends ClientDefinition> = AutoGeneratedClient['transferBot']
export type ListBots<_C extends ClientDefinition> = AutoGeneratedClient['listBots']
export type GetBot<_C extends ClientDefinition> = AutoGeneratedClient['getBot']
export type DeleteBot<_C extends ClientDefinition> = AutoGeneratedClient['deleteBot']
export type GetBotLogs<_C extends ClientDefinition> = AutoGeneratedClient['getBotLogs']
export type GetBotWebchat<_C extends ClientDefinition> = AutoGeneratedClient['getBotWebchat']
export type GetBotAnalytics<_C extends ClientDefinition> = AutoGeneratedClient['getBotAnalytics']
export type CreateWorkspace<_C extends ClientDefinition> = AutoGeneratedClient['createWorkspace']
export type GetWorkspace<_C extends ClientDefinition> = AutoGeneratedClient['getWorkspace']
export type UpdateWorkspace<_C extends ClientDefinition> = AutoGeneratedClient['updateWorkspace']
export type ListWorkspaces<_C extends ClientDefinition> = AutoGeneratedClient['listWorkspaces']
export type ChangeWorkspacePlan<_C extends ClientDefinition> = AutoGeneratedClient['changeWorkspacePlan']
export type DeleteWorkspace<_C extends ClientDefinition> = AutoGeneratedClient['deleteWorkspace']
export type CreateIntegration<_C extends ClientDefinition> = AutoGeneratedClient['createIntegration']
export type UpdateIntegration<_C extends ClientDefinition> = AutoGeneratedClient['updateIntegration']
export type ListIntegrations<_C extends ClientDefinition> = AutoGeneratedClient['listIntegrations']
export type GetIntegration<_C extends ClientDefinition> = AutoGeneratedClient['getIntegration']
export type GetIntegrationLogs<_C extends ClientDefinition> = AutoGeneratedClient['getIntegrationLogs']
export type GetIntegrationByName<_C extends ClientDefinition> = AutoGeneratedClient['getIntegrationByName']
export type DeleteIntegration<_C extends ClientDefinition> = AutoGeneratedClient['deleteIntegration']
export type ListWorkspaceMembers<_C extends ClientDefinition> = AutoGeneratedClient['listWorkspaceMembers']
export type DeleteWorkspaceMember<_C extends ClientDefinition> = AutoGeneratedClient['deleteWorkspaceMember']
export type CreateWorkspaceMember<_C extends ClientDefinition> = AutoGeneratedClient['createWorkspaceMember']
export type UpdateWorkspaceMember<_C extends ClientDefinition> = AutoGeneratedClient['updateWorkspaceMember']
export type Introspect<_C extends ClientDefinition> = AutoGeneratedClient['introspect']
export type CreateFile<_C extends ClientDefinition> = AutoGeneratedClient['createFile']
export type GetFile<_C extends ClientDefinition> = AutoGeneratedClient['getFile']
export type DownloadFile<_C extends ClientDefinition> = AutoGeneratedClient['downloadFile']
export type DeleteFile<_C extends ClientDefinition> = AutoGeneratedClient['deleteFile']
export type ListFiles<_C extends ClientDefinition> = AutoGeneratedClient['listFiles']
